#### CSC 180 Intelligent Systems 





# Lab 1:  Numpy, Scipy and Matplotlib -  high-performance vector operations


<img src="https://cdn-images-1.medium.com/fit/t/1600/480/1*Y2v3PrF1rUQRUHwOcXJznA.png" width="600">


# 1. Numpy

The `numpy` package (module) is used in almost all numerical computation using Python. It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. It is implemented in C and Fortran so when calculations are vectorized (formulated with vectors and matrices), performance is very good. 

To use `numpy` first import the module:

In [1]:
import numpy as np  # np is the most common import name for numpy

In the `numpy` package the terminology used for vectors, matrices and higher-dimensional data sets is *array*. 



## Creating `numpy` arrays (vectors or matrices)

There are a number of ways to initialize new numpy arrays, for example from

* a Python list or tuples
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.
* reading data from files

### From lists

For example, to create new vector and matrix arrays from Python lists we can use the `numpy.array` function.

In [2]:
# a vector: the argument to the array function is a Python list
v = np.array([1, 2, 3, 4])
v

array([1, 2, 3, 4])

In [3]:
# a matrix (or better a 2d array): the argument to the array function is a nested Python list
M = np.array([[1, 2], [3, 4]])
M

array([[1, 2],
       [3, 4]])

The `v` and `M` objects are both of the type `ndarray` that the `numpy` module provides.

In [4]:
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

The difference between the `v` and `M` arrays is only their shapes. We can get information about the shape of an array by using the `ndarray.shape` property.

In [5]:
v.shape

(4,)

In [6]:
M.shape

(2, 2)

The number of elements in the array is available through the `ndarray.size` property:

In [7]:
v.size

4

In [8]:
M.size  # be careful matlab size is shape with Numpy

4

***So far the `numpy.ndarray` looks much like a Python list. 

### Why not simply use Python lists for computations instead of creating a new array type?

There are several reasons:

* Numpy arrays are ***memory efficient*** and run ***much faster*** than Python lists in order to support ***big data***.
* Python lists DO NOT support ***mathematical functions*** such as matrix and dot multiplications, etc. Implementating such functions for Python lists would be very inefficient. 
* Python lists are very general. They can contain any kind of object. * Numpy arrays are  **homogeneous**. The type of the elements is determined when array is created.***


Using the `dtype` (data type) property of an `ndarray`, we can see what type each element of an array has:

In [9]:
M.dtype

dtype('int32')

We get an error if we try to assign a value of the wrong type to an element in a numpy array:

In [10]:
M[0, 0] = "hello"

ValueError: invalid literal for int() with base 10: 'hello'

If we want, we can ***explicitly define the type of the array data*** when we create it, using the `dtype` keyword argument: 

In [ ]:
M = np.array([[1, 2], [3, 4]], dtype='float32')
M

array([[1., 2.],
       [3., 4.]], dtype=float32)

Common type that can be used with `dtype` are: `int`, `float`, `complex`, `bool`, `object`, etc.

We can also explicitly define the **bit size** of the **data types**, for example: `int64`, `int16`, `float128`, `complex128`.

### Using functions to generate arrays

For larger arrays it is inpractical to initialize the data manually, using explicit python lists. Instead we can use one of the many functions in `numpy` that generates arrays of different forms. Some of the more common are:

#### arange

In [ ]:
# create a range

x = np.arange(0, 10, 1) # arguments: start, stop, step
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x = np.arange(-1, 1, 0.1)
x

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

#### linspace and logspace

In [ ]:
# using linspace, both end points ARE included
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [ ]:
np.logspace(0, 10, 10, base=10)

array([1.00000000e+00, 1.29154967e+01, 1.66810054e+02, 2.15443469e+03,
       2.78255940e+04, 3.59381366e+05, 4.64158883e+06, 5.99484250e+07,
       7.74263683e+08, 1.00000000e+10])

## Manipulating arrays

### Indexing

We can index elements in an array using the square bracket and indices:

In [ ]:
v = np.array([1, 2, 3, 4])

# v is a vector, and has only one dimension, taking one index
v[0]

1

In [ ]:
v = np.array([1, 2, 3, 4])
v[0]

1

In [ ]:
M = np.array([[1, 2], [3, 4]])

# M is a matrix, or a 2 dimensional array, taking two indices 
M[1, 1]

4

In [ ]:
M

array([[1, 2],
       [3, 4]])

In [ ]:
M[1, :] # row 1

array([3, 4])

In [ ]:
M[:, 1] # column 1

array([2, 4])

We can assign new values to elements in an array using indexing:

In [ ]:
M[0, 0] = 10
M

array([[10,  2],
       [ 3,  4]])

In [ ]:
# also works for rows and columns
M[0, :] = 0
M[:, 1] = -1

In [ ]:
M

array([[ 0, -1],
       [ 3, -1]])

### Index slicing

Index slicing is the technical name for the syntax `M[start:end:step]` to extract part of an array:

In [ ]:
A = np.array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [ ]:
A[1:3]

array([2, 3])

#### Array slices are *mutable*

If they are assigned a new value the original array from which the slice was extracted is modified:

In [ ]:
A[1:3] = [-2, -3]

A

array([ 1, -2, -3,  4,  5])

We can omit any of the three parameters in `M[start:end:step]`:

In [ ]:
A[::] # lower, upper, step all take the default values

In [ ]:
A[::2] # step is 2, lower and upper defaults to the beginning and end of the array

In [ ]:
A[:3] # first three elements

In [ ]:
A[3:] # elements from index 3

Negative indices counts from the end of the array (positive index from the begining):

In [ ]:
A = np.array([1, 2, 3, 4, 5])

In [ ]:
A[-1] # the last element in the array

In [ ]:
A[-3:] # the last three elements

### Index slicing works exactly the same way for multidimensional arrays:

You may also use an array or list as an index:

In [ ]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])

A   # a matrix

In [ ]:
row_indices = [1, 2, 3]
A[row_indices,:]

In [ ]:
col_indices = [1, 2, -1] # remember, index -1 means the last element
A[:,col_indices]

In [ ]:
# a block from the original array
A[1:4, 1:4]

## Array-oriented programming

### Vectorizing code is the key to writing code when handling big data. That means that as much as possible, a program should be written in terms of matrix (vector) operations.

### Scalar-array operations

We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.

In [ ]:
v1 = np.arange(0, 5)
v1

In [ ]:
v1 * 2

In [ ]:
v1 + 2

### Element-wise array-array operations

When we add, subtract, multiply and divide arrays with each other, the default behaviour is **element-wise** operations:

In [ ]:
A

In [ ]:
A * A # element-wise multiplication

### Matrix algebra

What about matrix mutiplication? We can use the `dot` function

In [ ]:
np.dot(A, A)

### Basic data analysis using numpy

Often it is useful to store datasets in Numpy arrays (matrix). Numpy provides a number of functions to calculate statistics of datasets in arrays.

In [ ]:
A

In [ ]:
np.shape(A)

#### mean

In [ ]:
np.mean(A[:, 3])

#### standard deviations and variance, min and max

In [ ]:
np.std(A[:, 3]), np.var(A[:, 3])

In [ ]:
# lowest value
A[:, 3].min()

In [ ]:
# highest value
A[:, 3].max()

#### sum, prod

In [ ]:
# sum up all elements
np.sum(A[:, 3])

In [ ]:
# product of all elements
np.prod(A[:, 3])

### Perform funcitons to entire matrix?

It is sometimes useful to apply the calculation to the entire array, and sometimes only on a row or column basis. Using the `axis` argument we can specify how these functions should behave: 

In [ ]:
from numpy import random

m = random.rand(3, 3)
m

In [ ]:
# global max
m.max()

Many other functions and methods in the `array` and `matrix` classes accept the same (optional) `axis` keyword argument.

In [ ]:
# max in each column
m.max(axis=0)

In [ ]:
# max in each row
m.max(axis=1)

## Reshaping, resizing and stacking arrays

The shape of an Numpy array can be modified without copying the underlaying data, which makes it a fast operation even for large arrays.

In [ ]:
A

In [ ]:
n, m = A.shape
n, m     # equivalent to print(n, m)

In [ ]:
B = A.reshape((1, n*m))  
B

We can also use the function `flatten` to make a higher-dimensional array into a vector. But this function create a seperate copy of the underlying data.

In [ ]:
B = A.flatten()  # because B's data is a seperate copy of A's,
B

## Type casting

Since Numpy arrays are *statically typed*, the type of an array does not change once created. But we can explicitly cast an array of some type to another using the `astype` functions. This always create a new array of new type:

In [ ]:
M = np.array([[1, 2], [3, 4]])

M

In [ ]:
M.dtype

In [ ]:
M2 = M.astype('float64')

M2

In [ ]:
M2.dtype

In [ ]:
M3 = M.astype(bool)

M3

# 2. Scipy:  a library for scientific computing
#### It provides many user-friendly and efficient numerical routines such as stats,  numerical integration and optimization.

In [ ]:
import numpy as np
import scipy.spatial.distance as sp_dist


x = np.random.randint(0, 2, size = 20)      # Return random integers from low (inclusive) to high (exclusive).
y = np.random.randint(0, 2, size = 20)

print (x)
print (y)
print (sp_dist.cosine(x,y))
print (sp_dist.euclidean(x,y))
print (sp_dist.jaccard(x,y))
print (sp_dist.hamming(x,y))

In [ ]:
from scipy.stats import linregress

a = [15, 12, 8, 8, 7, 7, 7, 6, 5, 3]
b = [10, 25, 17, 11, 13, 17, 20, 13, 9, 15]

linregress(a, b)

# 3. Matplotlib

####  (1) Use a magic command to enable figures in notebook!!!
%matplotlib inline    

####  (2) Import
import matplotlib.pyplot as plt

In [ ]:
# A magic command to enable matplotlib figures in notebook!!!
%matplotlib inline 

# import
import matplotlib.pyplot as plt
import numpy as np 


# create an empty figure

fig = plt.figure()  # an empty figure 

plt.figure(figsize=(20,5))  # optional

x = np.linspace(0, 2, 100)

plt.plot(x, x, label='linear')
plt.plot(x, x**2, label='quadratic')
plt.plot(x, x**3, label='cubic')

plt.xlabel('x label')
plt.ylabel('y label')

plt.title("Simple Plot")

plt.legend()

plt.show()

### Generate random data

In [ ]:
from numpy import random

In [ ]:
# uniform random numbers in [0,1]
random.rand(5,5)

In [ ]:
# standard normal distributed random numbers
random.randn(5,5)

In [ ]:
x = random.randn(10000)
plt.hist(x)
plt.show()

In [ ]:
np.random.randint(0, 2, size=10)   # Return random integers from low (inclusive) to high (exclusive)

In [ ]:
np.random.randint(0, 5, size=(2, 4))   # Return random integers from low (inclusive) to high (exclusive)